# SPDX-License-Identifier: MIT
# Copyright (c) 2026 K. S. Ernest (iFire) Lee

defmodule Taskweft.OpenPLC.GDScript do
  @moduledoc """
  Emit GDScript equivalent of the state machine `Taskweft.OpenPLC.PLCopen`
  would encode in FBD, from the same compact GRAFCET input (RFD 2143).
  RFD 2150 stage 1: the reader half of the GDScript <-> FBD transpiler
  (the writer half — GDScript parser -> FBD — stays parked).

  Semantics per scan (one `_process(delta)`):

    * SR flip-flops as booleans; step_<name>_active mirrors what
      `SR_L.Q` would hold in FBD.
    * Transitions fire when their upstream step is active AND their
      guards are met, in the order the compact GRAFCET's `S` array
      lists them (deterministic on a single scan).
    * Actions run while the step is active.
    * `^` initial step armed once via a `_first_scan` latch.

  The output is a `.gd` file the Godot Sandbox's SafeGDScript compiler
  can turn into a `.riscv` binary via RFD 2149's pipeline. No OpenPLC
  Editor needed for GDScript-authored plans.
  """

  @doc "Emit GDScript source for one compact GRAFCET map. Returns a string."
  def emit(%{"S" => steps, "V" => vars} = grafcet) do
    name = Map.get(grafcet, "sfc", "rectgtn_plan")
    {names, transitions} = walk(steps)

    var_decls =
      vars
      |> Map.keys()
      |> Enum.sort()
      |> Enum.map_join("\n", fn v -> "var done_#{v}: bool = false" end)

    step_decls =
      names
      |> Enum.map_join("\n", fn n -> "var step_#{n}_active: bool = false" end)

    tick_body = tick_body(names, transitions)

    """
    # Generated by Taskweft.OpenPLC.GDScript (RFD 2150 stage 1) from
    # compact GRAFCET #{name}. Feed to godot-sandbox's SafeGDScript
    # compiler to produce a .riscv binary loadable by the Sandbox node
    # (RFD 2149). The state-machine shape mirrors
    # Taskweft.OpenPLC.PLCopen.emit/1's FBD network.
    extends Node

    # done_* flags mirror V entries in the compact GRAFCET.
    #{var_decls}

    # step_<name>_active mirrors SR_L.Q for each step in the FBD.
    #{step_decls}

    var _first_scan: bool = true

    func _process(_delta: float) -> void:
    #{tick_body}
    """
  end

  # -- tick body ---------------------------------------------------------
  # Iterate transitions in S-array order; if the transition's sources are
  # all active and its guard atoms hold, activate the target and clear the
  # sources. Then run each active step's action (assign done_<var>).
  defp tick_body(names, transitions) do
    initial = "__init"

    first_scan =
      """
    \tif _first_scan:
    \t\tstep_#{initial}_active = true
    \t\t_first_scan = false
      """

    transition_lines =
      transitions
      |> Enum.map(&transition_line/1)
      |> Enum.join("\n")

    action_lines =
      names
      |> Enum.reject(&(&1 == initial))
      |> Enum.map(fn n -> "\tif step_#{n}_active:\n\t\tdone_#{n} = true" end)
      |> Enum.join("\n")

    [first_scan, transition_lines, action_lines] |> Enum.join("\n")
  end

  defp transition_line(%{sources: srcs, target: dst, atoms: atoms, delay: _}) do
    src_conds = Enum.map(srcs, fn s -> "step_#{s}_active" end)
    atom_conds = Enum.map(atoms, fn a -> a end)
    guard = Enum.join(src_conds ++ atom_conds, " and ")

    resets = Enum.map_join(srcs, "\n", fn s -> "\t\tstep_#{s}_active = false" end)

    "\tif #{guard}:\n\t\tstep_#{dst}_active = true\n#{resets}"
  end

  # -- walker (mirrors Taskweft.OpenPLC.PLCopen.walk/1) ------------------

  defp walk(steps) do
    {names, _} =
      Enum.reduce(steps, {[], nil}, fn row, {acc, _} ->
        case row do
          ["^"] -> {acc ++ ["__init"], "__init"}
          [head | _] when head in ["&>", "&<"] -> {acc, nil}
          [head | _] when head in ["|>", "|<", "!>"] ->
            raise "GDScript emit for #{inspect(head)} is staged; see RFD 2150"
          [head | _] when is_binary(head) and byte_size(head) > 0 and
                          (binary_part(head, 0, 1) == "%" or
                           binary_part(head, 0, 1) == "#") ->
            raise "GDScript emit for #{inspect(head)} is staged"
          [name, _, _, _] -> {acc ++ [name], name}
          _ -> {acc, nil}
        end
      end)

    {_, transitions, _, _} =
      Enum.reduce(steps, {nil, [], nil, nil}, fn row, {last, tacc, fp, fpen} ->
        case row do
          ["^"] -> {"__init", tacc, fp, fpen}
          ["&>" | children] -> {last, tacc, last, children}
          ["&<" | preds] -> {last, tacc, fp, {:conv, preds}}
          [name, when_expr, _, _] ->
            {srcs, fp2, fpen2} =
              case {fpen, fp} do
                {{:conv, preds}, _} -> {preds, fp, nil}
                {fanout_children, parent} when is_list(fanout_children) ->
                  if name in fanout_children do
                    rest = List.delete(fanout_children, name)
                    {[parent], parent, if(rest == [], do: nil, else: rest)}
                  else
                    {[last], fp, fpen}
                  end
                _ -> {[last], fp, fpen}
              end
            atoms = parse_atoms(when_expr)
            {name, tacc ++ [%{sources: srcs, target: name, atoms: atoms, delay: nil}],
             fp2, fpen2}
          _ -> {last, tacc, fp, fpen}
        end
      end)

    {names, transitions}
  end

  defp parse_atoms(""), do: []
  defp parse_atoms(nil), do: []
  defp parse_atoms(expr) when is_binary(expr) do
    expr
    |> String.split("&")
    |> Enum.map(&String.trim/1)
    |> Enum.reject(&(&1 == ""))
    |> Enum.map(fn "X." <> step -> "step_" <> step <> "_active"; a -> a end)
  end
end
